backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

site_url: https://isj-photography.netlify.app

logo_url: https://isj-photography.netlify.app/static/isjlogo-fa67cd99ab1df8e6e710334a6f973b90.svg

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: session
    label: Session
    folder: "src/pages/sessions"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: TemplateKey,
          name: templateKey,
          widget: hidden,
          default: session-page,
        }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown, required: false }
      - {
          label: How It Works,
          name: howItWorks,
          widget: markdown,
          required: false,
        }
      - {
          label: Pricing,
          name: pricing,
          widget: object,
          fields:
            [
              {
                label: Description,
                name: description,
                widget: markdown,
                required: false,
              },
              {
                label: Tables,
                name: tables,
                widget: list,
                fields:
                  [
                    { label: Title, name: title, widget: string },
                    { label: Price, name: price, widget: number },
                    {
                      label: Features,
                      name: features,
                      widget: list,
                      field: { label: Feature, name: feature, widget: string },
                    },
                  ],
              },
            ],
        }
      - {
          label: FAQs,
          name: faqs,
          widget: list,
          fields:
            [
              { label: Question, name: question, widget: string },
              { label: Answer, name: answer, widget: markdown },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          - {
              label: Slider Images,
              name: sliderImages,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Quote, name: quote, widget: text },
                  { label: Author, name: author, widget: string },
                ],
            }
          - {
              label: Timeline Images,
              name: timelineImages,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: string },
                ],
            }
          - { label: Ieashia Photo, name: ieashiaPhoto, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/wall-art/index.md"
        label: "Wall Art"
        name: "wallArt"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "wall-art",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/studio.md"
        label: "Studio"
        name: "studio"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/testimonials/index.md"
        label: Testimonials
        name: testimonials
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: testmonial-page,
            }
          - { label: Description, name: description, widget: text }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Author, name: author, widget: string },
                  { label: Quote, name: quote, widget: text },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/contact/index.md"
        label: Contact
        name: contact
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: contact-page,
            }
          - { label: Description, name: description, widget: text }
          - { label: Image, name: image, widget: image }
      - file: "src/pages/contact/thanks.md"
        label: Completed Contact
        name: completed contact
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: completed-contact,
            }
          - { label: Image, name: image, widget: image }
          - { label: Body, name: body, widget: markdown }
