backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

logo_url: https://isj-photography.netlify.app/static/isjlogo-fa67cd99ab1df8e6e710334a6f973b90.svg

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Post", name: "featuredpost", widget: "boolean" }
      - { label: "Featured Image", name: "featuredimage", widget: image }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }

  - name: Session
    label: session
    folder: "src/pages/sessions"
    create: true
    slug: "{{slug}}"
    fields:
      - {
          label: TemplateKey,
          name: templateKey,
          widget: hidden,
          default: session-page,
        }
      - { label: Title, name: title, widget: string }
      - { label: Body, name: body, widget: markdown }
      - { label: How It Works, name: howItWorks, widget: markdown }
      - {
          label: Pricings,
          name: pricings,
          widget: object,
          fields:
            [
              { label: Description, name: description, widget: markdown },
              {
                label: Tables,
                name: tables,
                widget: list,
                fields:
                  [
                    { label: Title, name: title, widget: string },
                    { label: Price, name: price, widget: number },
                    {
                      label: Features,
                      name: features,
                      widget: list,
                      field: { label: Feature, name: feature, widget: string },
                    },
                  ],
              },
              {
                label: After Description,
                name: afterDescription,
                widget: text,
              },
            ],
        }
      - {
          label: FAQs,
          name: faqs,
          widget: list,
          fields:
            [
              { label: Question, name: question, widget: string },
              { label: Answer, name: answer, widget: markdown },
            ],
        }

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "index-page",
            }
          # - { label: Title, name: title, widget: string }
          # - { label: Image, name: image, widget: image }
          # - { label: Heading, name: heading, widget: string }
          # - { label: Subheading, name: subheading, widget: string }
          # - { label: Letter, name: letter, widget: markdown }
          # - {
          #     label: Mainpitch,
          #     name: mainpitch,
          #     widget: object,
          #     fields:
          #       [
          #         { label: Title, name: title, widget: string },
          #         { label: Description, name: description, widget: text },
          #       ],
          #   }
          # - { label: Description, name: description, widget: string }
          # - {
          #     label: Intro,
          #     name: intro,
          #     widget: object,
          #     fields:
          #       [
          #         { label: Heading, name: heading, widget: string },
          #         { label: Description, name: description, widget: text },
          #         {
          #           label: Blurbs,
          #           name: blurbs,
          #           widget: list,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Text, name: text, widget: text },
          #             ],
          #         },
          #       ],
          #   }
          - {
              label: Timeline Images,
              name: timelineImages,
              widget: list,
              fields:
                [
                  { label: Image, name: image, widget: image },
                  { label: Text, name: text, widget: string },
                ],
            }
          - { label: Ieashia Photo, name: ieashiaPhoto, widget: image }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/about/studio.md"
        label: "Studio"
        name: "studio"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "about-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "product-page",
            }
          - { label: Title, name: title, widget: string }
          - { label: Image, name: image, widget: image }
          - { label: Heading, name: heading, widget: string }
          - { label: Description, name: description, widget: string }
          # - {
          #     label: Intro,
          #     name: intro,
          #     widget: object,
          #     fields:
          #       [
          #         { label: Heading, name: heading, widget: string },
          #         { label: Description, name: description, widget: text },
          #         {
          #           label: Blurbs,
          #           name: blurbs,
          #           widget: list,
          #           fields:
          #             [
          #               { label: Image, name: image, widget: image },
          #               { label: Text, name: text, widget: text },
          #             ],
          #         },
          #       ],
          #   }
          - {
              label: Main,
              name: main,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: text },
                  {
                    label: Image1,
                    name: image1,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image2,
                    name: image2,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                  {
                    label: Image3,
                    name: image3,
                    widget: object,
                    fields:
                      [
                        { label: Image, name: image, widget: image },
                        { label: Alt, name: alt, widget: string },
                      ],
                  },
                ],
            }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Quote, name: quote, widget: string },
                  { label: Author, name: author, widget: string },
                ],
            }
          - { label: Full_image, name: full_image, widget: image }
          - {
              label: Pricing,
              name: pricing,
              widget: object,
              fields:
                [
                  { label: Heading, name: heading, widget: string },
                  { label: Description, name: description, widget: string },
                  {
                    label: Plans,
                    name: plans,
                    widget: list,
                    fields:
                      [
                        { label: Plan, name: plan, widget: string },
                        { label: Price, name: price, widget: string },
                        {
                          label: Description,
                          name: description,
                          widget: string,
                        },
                        { label: Items, name: items, widget: list },
                      ],
                  },
                ],
            }
      - file: "src/pages/testimonials/index.md"
        label: Testimonials
        name: testimonials
        fields:
          - {
              label: Template Key,
              name: templateKey,
              widget: hidden,
              default: testmonial-page,
            }
          - { label: Description, name: description, widget: string }
          - {
              label: Testimonials,
              name: testimonials,
              widget: list,
              fields:
                [
                  { label: Author, name: author, widget: string },
                  { label: Quote, name: quote, widget: string },
                  { label: Image, name: image, widget: image },
                ],
            }
      - file: "src/pages/blank.md"
        label: "Blank"
        name: "blank"
        fields:
          - {
              label: "Template Key",
              name: "templateKey",
              widget: "hidden",
              default: "blank-page",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
